version: "3.3"
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - mosquitto_conf:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data:ro
      - mosquitto_log:/mosquitto/log:ro
    networks:
      - mqttnet
    ports:
      - 9001:9001
      - 1883:1883

  app-container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mqtt
volumes:
  mosquitto_conf:
  mosquitto_data:
  mosquitto_log:
networks:
  mqttnet:
    driver: bridge
